In [3]:
import pandas as pd
import numpy as np

In [11]:
df=pd.read_csv("Binance_EOSUSDT_d.csv")
high=pd.DataFrame(df['high'],range(0,100))
# df

,unix,date,symbol,open,high,low,close,Volume EOS,Volume USDT,tradecount
0,1635724800000,2021-11-01 00:00:00,EOS/USDT,4.6370,4.7200,4.6010,4.6860,981157.20,4.581967e+06,18006
1,1635638400000,2021-10-31 00:00:00,EOS/USDT,4.4800,4.7730,4.4430,4.6370,23251890.90,1.065591e+08,274574
2,1635552000000,2021-10-30 00:00:00,EOS/USDT,4.5020,4.5240,4.3480,4.4800,12769295.90,5.678941e+07,114377
3,1635465600000,2021-10-29 00:00:00,EOS/USDT,4.4010,4.5420,4.3740,4.5020,13111625.60,5.847186e+07,118427
4,1635379200000,2021-10-28 00:00:00,EOS/USDT,4.1510,4.4950,4.1330,4.4010,24985864.10,1.084351e+08,249012
...,...,...,...,...,...,...,...,...,...,...
1249,1527811200000,2018-06-01 00:00:00,EOS/USDT,12.2351,12.3889,11.8354,12.2048,5946136.88,7.216073e+07,53090
1250,1527724800000,2018-05-31 00:00:00,EOS/USDT,11.8712,12.7400,11.8116,12.2353,6540020.80,8.045451e+07,55055
1251,1527638400000,2018-05-30 00:00:00,EOS/USDT,12.1113,12.8200,11.6206,11.8968,6514864.18,7.855943e+07,52521
1252,1527552000000,2018-05-29 00:00:00,EOS/USDT,11.4853,12.4650,10.7000,12.1112,6709192.34,7.816397e+07,67086
1253,1527465600000,2018-05-28 00:00:00,EOS/USDT,12.4900,12.6500,11.2800,11.4788,3494258.32,4.169752e+07,33754

In [16]:
Volume_Eos= df["Volume EOS"].values
Volume_USDT= df["Volume USDT"].values
Correlation_Coefficient = np.corrcoef(Volume_Eos, Volume_USDT)
print(f"Correlation Coefficient is: {Correlation_Coefficient}")

Correlation Coefficient is: [[1.         0.89127292]
 [0.89127292 1.        ]]